import {
  Gender,
  UserRole,
  StudentStatus,
  StaffPosition,
} from '../generated/prisma';

export const mockUsers = [
  // ============================================
  // STUDENTS
  // ============================================
  {
    utaId: '1001000001',
    netId: 'axjh03',
    fName: 'Aalok',
    lName: 'Jha',
    email: 'axj2203@uta.edu',
    phone: 8175550101,
    passwordHash: 'P@ssw0rd123', // plain password for now
    dob: new Date('2003-05-15'),
    gender: Gender.MALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.APPLICANT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000002',
    netId: 'jdoe01',
    fName: 'John',
    mName: 'Quincy',
    lName: 'Doe',
    email: 'jdoe01@uta.edu',
    phone: 8175550102,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2002-11-20'),
    gender: Gender.MALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000003',
    netId: 'esto22',
    fName: 'Emily',
    lName: 'Stone',
    email: 'esto22@uta.edu',
    phone: 8175550103,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2003-08-10'),
    gender: Gender.FEMALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000004',
    netId: 'mxj4444',
    fName: 'Michael',
    lName: 'Johnson',
    email: 'mxj4444@uta.edu',
    phone: 8175550104,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2003-03-22'),
    gender: Gender.MALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: true, // ADA access required
  },
  {
    utaId: '1001000005',
    netId: 'sxm5555',
    fName: 'Sophia',
    lName: 'Martinez',
    email: 'sxm5555@uta.edu',
    phone: 8175550105,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2002-09-14'),
    gender: Gender.FEMALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.APPLICANT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000006',
    netId: 'cxw6666',
    fName: 'Christopher',
    lName: 'Williams',
    email: 'cxw6666@uta.edu',
    phone: 8175550106,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2003-01-05'),
    gender: Gender.MALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000007',
    netId: 'axp7777',
    fName: 'Alicia',
    lName: 'Patel',
    email: 'axp7777@uta.edu',
    phone: 8175550107,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2002-07-28'),
    gender: Gender.FEMALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: false,
  },

  // ============================================
  // STAFF
  // ============================================
  {
    utaId: '1001000101',
    netId: 'sxr5555',
    fName: 'Sarah',
    lName: 'Admin',
    email: 'sxr5555@uta.edu',
    phone: 8175550201,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2001-08-30'),
    gender: Gender.FEMALE,
    role: UserRole.STAFF,
    studentStatus: null,
    staffPosition: StaffPosition.RESIDENT_A,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000102',
    netId: 'rxb6666',
    fName: 'Robert',
    lName: 'Brown',
    email: 'rxb6666@uta.edu',
    phone: 8175550202,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2000-12-15'),
    gender: Gender.MALE,
    role: UserRole.STAFF,
    studentStatus: null,
    staffPosition: StaffPosition.RESIDENT_A,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000103',
    netId: 'jxg7777',
    fName: 'Jennifer',
    lName: 'Garcia',
    email: 'jxg7777@uta.edu',
    phone: 8175550203,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('1999-06-22'),
    gender: Gender.FEMALE,
    role: UserRole.STAFF,
    studentStatus: null,
    staffPosition: StaffPosition.MANAGEMENT,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000104',
    netId: 'txk8888',
    fName: 'Thomas',
    lName: 'Khan',
    email: 'txk8888@uta.edu',
    phone: 8175550204,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2001-03-10'),
    gender: Gender.MALE,
    role: UserRole.STAFF,
    studentStatus: null,
    staffPosition: StaffPosition.DESK_A,
    requiresAdaAccess: false,
  },
  {
    utaId: '1001000105',
    netId: 'dxl9999',
    fName: 'Diana',
    lName: 'Lopez',
    email: 'dxl9999@uta.edu',
    phone: 8175550205,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2000-09-05'),
    gender: Gender.FEMALE,
    role: UserRole.STAFF,
    studentStatus: null,
    staffPosition: StaffPosition.SECURITY,
    requiresAdaAccess: false,
  },

  // ============================================
  // ADMIN
  // ============================================
  {
    utaId: '1001000201',
    netId: 'admin01',
    fName: 'Admin',
    lName: 'Account',
    email: 'admin01@uta.edu',
    phone: 8175550301,
    passwordHash: 'P@ssw0rd123',
    dob: new Date('1998-04-12'),
    gender: Gender.MALE,
    role: UserRole.ADMIN,
    studentStatus: null,
    staffPosition: null,
    requiresAdaAccess: false,
  },
  // Test User from users.json
  {
    utaId: '1001999999',
    netId: 'axr0966',
    fName: 'atiq',
    lName: 'rahman',
    email: 'axr0966@mavs.uta.edu',
    phone: '817-555-9999',
    passwordHash: 'P@ssw0rd123',
    dob: new Date('2000-01-01'),
    gender: Gender.MALE,
    role: UserRole.STUDENT,
    studentStatus: StudentStatus.RESIDENT,
    requiresAdaAccess: false,
  }
];
